[package]
name = "raf_newick_impl"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
smallvec = { workspace = true }
raf_array = { path = "../../raf_array" }
raf_fnv1a_hasher = { path = "../../raf_fnv1a_hasher" }
