[package]
name = "raf_fnv1a_hasher"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
getrandom = { workspace = true, optional = true }

[features]
default = ["getrandom"]
getrandom = ["dep:getrandom"]
