[package]
name = "raf_shadow_alloc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
ctor = { workspace = true }
region = { workspace = true }
